version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  lint_and_test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Authenticate with NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - node/with-cache:
          steps:
            - run:
                name: Install
                command: npm install
            - run:
                name: Lint
                command: npm run lint
            - run:
                name: Test
                command: npm run test
  publish:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Publish to NPM
          command: |
            set -e

            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

            NAME=$(node -p "require('./package').name")
            VERSION=$(node -p "require('./package').version")
            PUBLISHED_VERSION=$(npm view $NAME version)

            if [ "$VERSION" != "$PUBLISHED_VERSION" ]
            then
              npm ci
              npm publish
            fi

workflows:
  commit-workflow:
    jobs:
      - lint_and_test
      - publish:
          requires:
            - lint_and_test
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
